apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-develop
  namespace: python-app-develop
  labels:
    app: python-app-develop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app-develop
  template:
    metadata:
      labels:
        app: python-app-develop
    spec:
      containers:
        - name: python-container
          image: guptatrng/python-app-develop-develop:950fcd2c4dc546e3caf4b1df92fea89666e7f735
          ports:
            - containerPort: 5000
      resource:
